### PR TITLE
Adding sqlite as BuildRequires for more modern platforms

### PR DESCRIPTION
**Pull request by rbrunckhorst**

### CODE REVIEW

**Comment by adeason** [comment]
When you say we need 'sqlite', I think you mean specifically the sqlite3 command, right? (we use this in the tests for some bulk loading/dumping of db data) that is, we can use sqlite via sqlalchemy okay, but we're missing the sqlite3 command. do I understand that correctly?

if that's right, I just want to make the commit message clearer about this

**Comment by rbrunckhorst** [comment]
Hi Andrew,

yes with sqlite I mean the binary sqlite3.
sqlite3 is used in the tests. And if the tests fails during an rbmbuild 
session the building of the package fails.
sqlite3 is included in rpm-package sqlite.

At the moment the commit message is:
Adding sqlite as BuildRequires for more modern platforms
sqlite is needed to run the tests after building.
sqlite package is installed per default on RHEL7 for rpm/yum stuff.
In more modern distros like RHEL8 or Fedora this dependency is
done via package sqlite-libs and sqlite is not installed.

So if I understand that correctly it should be something like:
Adding /usr/bin/sqlite3 as BuildRequires for platforms where the
rpm-package sqlite is not installed per default.
In more modern distress like RHEL8 or Fedora sqlite-libs is installed 
for
rpm dependency stuff which doesn't include sqlite3.
??

**Comment by adeason** [comment]
I pushed a suggested commit message. If that looks okay to you, I'll
merge it, or feel free to change it if you want.

-- 
Andrew Deason
***@***.***

**Review by adeason — APPROVED** [review]

**Comment by rbrunckhorst** [comment]
Looks fine.

Thank you.

--
Ralf Brunckhorst
***@***.***

**Pull request merged**
